package main

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/mtreilly/agent-discord/gosdk/discord/types"
	"github.com/mtreilly/agent-discord/gosdk/discord/webhook"
)

func main() {
	// Get webhook URL from environment
	webhookURL := os.Getenv("DISCORD_WEBHOOK")
	if webhookURL == "" {
		log.Fatal("DISCORD_WEBHOOK environment variable is required")
	}

	// Create webhook client
	client, err := webhook.NewClient(
		webhookURL,
		webhook.WithMaxRetries(3),
		webhook.WithTimeout(30*time.Second),
	)
	if err != nil {
		log.Fatalf("Failed to create webhook client: %v", err)
	}

	ctx := context.Background()

	// Example 1: Send a single text file
	fmt.Println("Example 1: Sending message with text file...")
	err = sendTextFile(ctx, client)
	if err != nil {
		log.Fatalf("Failed to send text file: %v", err)
	}
	fmt.Println("✓ Text file sent")

	time.Sleep(2 * time.Second)

	// Example 2: Send multiple files
	fmt.Println("\nExample 2: Sending message with multiple files...")
	err = sendMultipleFiles(ctx, client)
	if err != nil {
		log.Fatalf("Failed to send multiple files: %v", err)
	}
	fmt.Println("✓ Multiple files sent")

	time.Sleep(2 * time.Second)

	// Example 3: Send log file with embed
	fmt.Println("\nExample 3: Sending log file with rich embed...")
	err = sendLogWithEmbed(ctx, client)
	if err != nil {
		log.Fatalf("Failed to send log with embed: %v", err)
	}
	fmt.Println("✓ Log file with embed sent")

	fmt.Println("\n✅ All examples completed successfully!")
}

func sendTextFile(ctx context.Context, client *webhook.Client) error {
	content := `This is a sample text file.
It contains multiple lines.
Sent via Discord webhook with file upload support!`

	msg := &types.WebhookMessage{
		Content:  "Here's a text file:",
		Username: "File Upload Bot",
	}

	files := []webhook.FileAttachment{
		{
			Name:        "sample.txt",
			ContentType: "text/plain",
			Reader:      strings.NewReader(content),
			Size:        int64(len(content)),
		},
	}

	return client.SendWithFiles(ctx, msg, files)
}

func sendMultipleFiles(ctx context.Context, client *webhook.Client) error {
	// Create sample files
	file1 := "# Project Report\n\n## Summary\n\nEverything is working great!"
	file2 := `{
  "status": "success",
  "files_uploaded": 2,
  "timestamp": "2025-11-08T12:00:00Z"
}`
	file3 := "package main\n\nfunc main() {\n\tprintln(\"Hello, Discord!\")\n}"

	msg := &types.WebhookMessage{
		Content: "📁 Uploading multiple files:",
	}

	files := []webhook.FileAttachment{
		{
			Name:        "report.md",
			ContentType: "text/markdown",
			Reader:      strings.NewReader(file1),
			Size:        int64(len(file1)),
		},
		{
			Name:        "metadata.json",
			ContentType: "application/json",
			Reader:      strings.NewReader(file2),
			Size:        int64(len(file2)),
		},
		{
			Name:        "example.go",
			ContentType: "text/plain",
			Reader:      strings.NewReader(file3),
			Size:        int64(len(file3)),
		},
	}

	return client.SendWithFiles(ctx, msg, files)
}

func sendLogWithEmbed(ctx context.Context, client *webhook.Client) error {
	// Create a sample log file
	logContent := `[2025-11-08 12:00:01] INFO: Application started
[2025-11-08 12:00:02] INFO: Connected to database
[2025-11-08 12:00:03] INFO: Server listening on :8080
[2025-11-08 12:00:10] WARN: High memory usage detected
[2025-11-08 12:00:15] INFO: Request processed in 234ms
[2025-11-08 12:00:20] ERROR: Failed to connect to external API
[2025-11-08 12:00:21] INFO: Retrying with backoff...
[2025-11-08 12:00:23] INFO: Connection successful
`

	now := time.Now()
	msg := &types.WebhookMessage{
		Content: "📋 Application logs attached",
		Embeds: []types.Embed{
			{
				Title:       "Log File Summary",
				Description: "Recent application logs with errors and warnings",
				Color:       0xFFA500, // Orange
				Timestamp:   &now,
				Fields: []types.EmbedField{
					{
						Name:   "Level",
						Value:  "⚠️ Contains warnings and errors",
						Inline: true,
					},
					{
						Name:   "Lines",
						Value:  "8 entries",
						Inline: true,
					},
					{
						Name:   "Time Range",
						Value:  "12:00:01 - 12:00:23",
						Inline: true,
					},
					{
						Name:   "Issues Found",
						Value:  "• High memory usage\n• API connection failure (resolved)",
						Inline: false,
					},
				},
				Footer: &types.EmbedFooter{
					Text: "Generated by Discord Go SDK",
				},
			},
		},
	}

	files := []webhook.FileAttachment{
		{
			Name:        "application.log",
			ContentType: "text/plain",
			Reader:      strings.NewReader(logContent),
			Size:        int64(len(logContent)),
		},
	}

	return client.SendWithFiles(ctx, msg, files)
}

// Example 4: Send a simulated image (demonstrating binary content)
func sendImage(ctx context.Context, client *webhook.Client) error {
	// In a real application, you would read an actual image file
	// For this example, we'll create dummy binary content
	imageData := bytes.Repeat([]byte{0xFF, 0xD8, 0xFF, 0xE0}, 1000) // JPEG header pattern

	msg := &types.WebhookMessage{
		Content: "🖼️ Image upload example",
	}

	files := []webhook.FileAttachment{
		{
			Name:        "example.jpg",
			ContentType: "image/jpeg",
			Reader:      bytes.NewReader(imageData),
			Size:        int64(len(imageData)),
		},
	}

	return client.SendWithFiles(ctx, msg, files)
}
